/**
 * Generates docs/commands.md from the live Commander tree so the reference
 * never drifts from the code. Run with: pnpm docs:commands
 */
import fs from 'node:fs';
import path from 'node:path';
import { PassThrough, Writable } from 'node:stream';
import type { Command, Option } from 'commander';
import { COMMAND_META, commandPath } from '../src/cli/catalog.js';
import { createProgram } from '../src/cli/program.js';
import { EXIT_CODE_DESCRIPTIONS } from '../src/errors/exit-codes.js';

const sink = new Writable({ write: (_c, _e, cb) => cb() });
const program = createProgram(
  {
    stdout: sink,
    stderr: sink,
    stdin: new PassThrough(),
    env: {},
    cwd: process.cwd(),
    stdinIsTTY: false,
    stdoutIsTTY: false,
    stderrIsTTY: false,
  },
  {},
  { exitCode: 0 },
  'text',
);

function optionRow(o: Option): string {
  const def =
    o.defaultValue !== undefined && o.defaultValue !== false
      ? ` (default: \`${String(o.defaultValue)}\`)`
      : '';
  const choices = o.argChoices ? ` — one of: ${o.argChoices.map((c) => `\`${c}\``).join(', ')}` : '';
  return `| \`${o.flags.replace(/\|/g, '\\|')}\` | ${o.description}${choices}${def} |`;
}

function usage(cmd: Command, parents: string[]): string {
  const args = cmd.registeredArguments.map((a) => (a.required ? `<${a.name()}>` : `[${a.name()}]`));
  return ['gvids', ...parents, cmd.name(), ...args].join(' ');
}

const out: string[] = [
  '# Command reference',
  '',
  '<!-- Generated by scripts/generate-command-docs.ts — do not edit by hand. Run: pnpm docs:commands -->',
  '',
  'Every command accepts the global options below. Commands that take a video accept a file ID, a',
  '`docs.google.com/videos/…` URL or a `drive.google.com/…` URL.',
  '',
  '## Global options',
  '',
  '| Option | Description |',
  '| --- | --- |',
  ...program.options.filter((o) => !o.hidden).map(optionRow),
  '',
  '## Exit codes',
  '',
  '| Code | Meaning |',
  '| --- | --- |',
  ...Object.entries(EXIT_CODE_DESCRIPTIONS).map(([code, text]) => `| ${code} | ${text} |`),
  '',
  '## Output',
  '',
  'By default every command prints exactly one JSON envelope on stdout (one line; `--pretty` indents it):',
  '',
  '```json',
  '{"ok":true,"data":{"…":"…"},"error":null}',
  '{"ok":false,"data":null,"error":{"code":"LOGIN_REQUIRED","message":"…","exitCode":3,"retryable":false,"needsUser":true,"next":["gvids browser login"]}}',
  '```',
  '',
  'The exit code is 0 exactly when `ok` is true. Warnings travel in the envelope (`"warnings": [...]`).',
  'stderr stays silent unless `--progress` (JSON-line events) or `--verbose`/`--debug` (JSON-line logs).',
  '`--human` prints human-readable output instead. Exceptions: `guide` prints Markdown and `completion` a',
  'shell script (unless `--json`), `mcp` speaks MCP on stdio. `--dry-run` validates the arguments and',
  'describes the command without running it (it wins over `--detach`).',
  '',
  'Each command below lists its **effect** (read, write, destructive), its **backend** (local, drive,',
  'browser, drive|browser, oauth) and flags: needs `--yes`, uses AI allowance, slow, needs a person.',
  '',
  '## Commands',
  '',
];

function metaLine(cmd: Command): string {
  const meta = COMMAND_META[commandPath(cmd)];
  if (!meta) return '';
  const flags = [
    `effect: **${meta.effect}**`,
    `backend: \`${meta.backend}\``,
    ...(meta.confirm === 'always'
      ? ['needs `--yes`']
      : meta.confirm === 'conditional'
        ? ['may need `--yes`']
        : []),
    ...(meta.aiQuota === true ? ['uses AI allowance'] : meta.aiQuota ? ['may use AI allowance'] : []),
    ...(meta.slow ? ['slow (consider `--detach`)'] : []),
    ...(meta.human ? ['needs a person'] : []),
    ...(meta.idempotent ? ['idempotent'] : []),
  ];
  return `${flags.join(' · ')}${meta.note ? `  \n${meta.note}` : ''}`;
}

function walk(cmd: Command, parents: string[]): void {
  for (const sub of cmd.commands) {
    if (sub.name() === 'help') continue;
    const title = [...parents, sub.name()].join(' ');
    const aliases = sub.aliases().length
      ? ` (alias: ${sub
          .aliases()
          .map((a) => `\`${a}\``)
          .join(', ')})`
      : '';
    out.push(`### gvids ${title}${aliases}`, '', sub.description(), '');
    const meta = sub.commands.length === 0 ? metaLine(sub) : '';
    if (meta) out.push(meta, '');
    if (sub.commands.length === 0 || sub.registeredArguments.length > 0) {
      out.push('```', usage(sub, parents), '```', '');
    }
    const args = sub.registeredArguments;
    if (args.length) {
      out.push('| Argument | Description |', '| --- | --- |');
      for (const a of args) {
        const choices = a.argChoices ? ` — one of: ${a.argChoices.map((c) => `\`${c}\``).join(', ')}` : '';
        out.push(`| \`${a.name()}\` | ${a.description}${choices} |`);
      }
      out.push('');
    }
    const opts = sub.options.filter((o) => !o.hidden);
    if (opts.length) {
      out.push('| Option | Description |', '| --- | --- |', ...opts.map(optionRow), '');
    }
    walk(sub, [...parents, sub.name()]);
  }
}

walk(program, []);
const target = path.join(process.cwd(), 'docs', 'commands.md');
const text = `${out.join('\n').trimEnd()}\n`;
if (process.argv.includes('--check')) {
  // CI mode: fail when the committed reference no longer matches the code.
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
  if (current !== text) {
    console.error(`${target} is out of date. Run: pnpm docs:commands`);
    process.exit(1);
  }
  console.log(`${target} is up to date.`);
} else {
  fs.writeFileSync(target, text, 'utf8');
  console.log(`Wrote ${target}`);
}
